#ifndef DISPLAY_H
#define DISPLAY_H

// only function publicly avaliable, from which thread is created
void display_update(void * string, void * signal);

#define LV_COLOR_WHITE 255
#define LV_COLOR_BLACK 0

// create style attributes used by many constant styles
#define PAD_TOP LV_STYLE_CONST_PAD_TOP(0)
#define PAD_BOTTOM LV_STYLE_CONST_PAD_BOTTOM(0)
#define PAD_LEFT LV_STYLE_CONST_PAD_LEFT(0)
#define PAD_RIGHT LV_STYLE_CONST_PAD_RIGHT(0)
#define OPA LV_STYLE_CONST_OPA(LV_OPA_COVER)
#define BG_COLOR LV_STYLE_CONST_BG_COLOR(LV_COLOR_WHITE)
#define BG_GRAD_COLOR LV_STYLE_CONST_BG_GRAD_COLOR(LV_COLOR_WHITE)
#define RADIUS LV_STYLE_CONST_RADIUS(0)
#define BORDER_COLOR LV_STYLE_CONST_BORDER_COLOR(LV_COLOR_BLACK)
#define BORDER_OPA LV_STYLE_CONST_BORDER_OPA(LV_OPA_COVER)
#define BORDER_WIDTH LV_STYLE_CONST_BORDER_WIDTH(0)
#define BORDER_SIDE LV_STYLE_CONST_BORDER_SIDE(LV_BORDER_SIDE_NONE)
#define SHADOW_COLOR LV_STYLE_CONST_SHADOW_COLOR(LV_COLOR_BLACK)
#define SHADOW_WIDTH LV_STYLE_CONST_SHADOW_WIDTH(0)
#define TEXT_OPA LV_STYLE_CONST_TEXT_OPA(LV_OPA_COVER)
#define TEXT_COLOR LV_STYLE_CONST_TEXT_COLOR(LV_COLOR_BLACK)
#define TEXT_LETTER_SPACE LV_STYLE_CONST_TEXT_LETTER_SPACE(0)
#define TEXT_LINE_SPACE LV_STYLE_CONST_TEXT_LINE_SPACE(2)
#define IMG_OPA LV_STYLE_CONST_IMG_OPA(LV_OPA_COVER)
#define IMG_RECOLOR LV_STYLE_CONST_IMG_RECOLOR(LV_COLOR_BLACK)
#define LINE_OPA LV_STYLE_CONST_LINE_OPA(LV_OPA_COVER)
#define LINE_COLOR LV_STYLE_CONST_LINE_COLOR(LV_COLOR_BLACK)
#define LINE_WIDTH LV_STYLE_CONST_LINE_WIDTH(2)
#define LINE_ROUNDED LV_STYLE_CONST_LINE_ROUNDED(0)
#define TEXT_FONT LV_STYLE_CONST_TEXT_FONT(&lv_font_montserrat_16)

#endif